# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the project files
COPY . .

# Build the project
RUN npm run build

# Expose any ports if needed (optional)

# Set environment variables from Docker if desired (they can also be set externally)
# ENV METABASE_URL=https://your-metabase-instance.com \
#     METABASE_USERNAME=your_username \
#     METABASE_PASSWORD=your_password

# Use the node binary to run the built server
CMD ["node", "build/index.js"]
